var redirects = {
  '?page_id=17': '/impressum/'
  '?page_id=29': '/cloud_computing_fundamentals/',
  '?page_id=32': '/cloud_service_models/'
  '?page_id=45': '/infrastructure_as_a_service/'
  '?page_id=64': '/platform_as_a_service/'
  '?page_id=71': '/software_as_a_service/'
  '?page_id=86': '/'
  '?page_id=38': '/cloud_computing_fundamentals/#cloud_deployment_models'
  '?page_id=90': '/public_cloud/'
  '?page_id=95': '/private_cloud/'
  '?page_id=101': '/community_cloud/'
  '?page_id=106': '/hybrid_cloud/'
  '?page_id=130': '/cloud_offerings/'
  '?page_id=132': '/cloud_offerings/#cloud_environments'
  '?page_id=147': '/elastic_infrastructure/'
  '?page_id=156': '/node_based_availability/'
  '?page_id=152': '/environment_based_availability/'
  '?page_id=136': '/cloud_offerings/#storage_offerings'
  '?page_id=161': '/strict_consistency/'
  '?page_id=167': '/eventual_consistency/'
  '?page_id=173': '/relational_database/'
  '?page_id=178': '/blob_storage/'
  '?page_id=182': '/block_storage/'
  '?page_id=186': '/key_value_storage/'
  '?page_id=138': '/cloud_offerings/#communication_offerings'
  '?page_id=195': '/message_oriented_middleware/'
  '?page_id=191': '/message_oriented_middleware/'
  '?page_id=199': '/exactly_once_delivery/'
  '?page_id=204': '/at_least_once_delivery/'
  '?page_id=212': '/cloud_application_architectures/'
  '?page_id=214': '/cloud_application_architectures/#fundamental_cloud_architectures'
  '?page_id=240': '/distributed_application/'
  '?page_id=245': '/loose_coupling/'
  '?page_id=251': '/stateless_component/'
  '?page_id=255': '/idempotent_processor/'
  '?page_id=219': '/cloud_application_management/#management_components/'
  '?page_id=260': '/map_reduce/'
  '?page_id=265': '/elasticity_manager/'
  '?page_id=269': '/elastic_load_balancer/'
  '?page_id=273': '/elastic_queue/'
  '?page_id=221': '/cloud_application_management/#management_processes'
  '?page_id=278': '/watchdog/'
  '?page_id=284': '/update_transition_process/'
  '?page_id=223': '/cloud_application_architectures/#multi_tenancy/'
  '?page_id=291': '/shared_component/'
  '?page_id=295': '/tenant_isolated_component/'
  '?page_id=299': '/dedicated_component/'
};

(function() {
  var s = document.location.search;
  if (s in redirects) {
    window.location.replace(redirects[s]);
  }
})();